// [语言][0=标题，1=描述]
typedef const char* LangPair[2];

// 0:简体中文  1:英文
const LangPair answer_list[][2] = {
    {{"一切随缘，勿强求", "不要过于强迫或强求事情发生，让事情自然发展。"}, {"Let things flow naturally", "Do not force or insist too much; let things happen naturally."}},
    {{"再考虑一下", "在做出决定之前，需要更多时间来思考和评估。"}, {"Think it over", "More time is needed to think and evaluate before making a decision."}},
    {{"现在不是时候", "目前可能不是采取行动或做决定的最佳时机。"}, {"Now is not the time", "Now may not be the best time to act or make a decision."}},
    {{"非常好的主意", "这个想法或提议是非常好的，值得考虑或实施。"}, {"Excellent idea", "This idea or suggestion is very good and worth considering or implementing."}},
    {{"结果可能出乎你的意料", "最终的结果可能与你最初的期望或预测不同。"}, {"The outcome may surprise you", "The final result may differ from your initial expectations or predictions."}},
    {{"需要更多的信息", "在做出决定之前，需要收集更多的数据或信息。"}, {"More information is needed", "More data or information needs to be collected before making a decision."}},
    {{"是的，绝对", "这是一个坚定的、积极的回答，表明完全同意或支持。"}, {"Yes, definitely", "This is a firm and positive answer, indicating complete agreement or support."}},
    {{"不，放弃吧", "这是一个否定的回答，建议不要继续追求或放弃某事。"}, {"No, let it go", "This is a negative answer, suggesting not to continue pursuing or to give up something."}},
    {{"你可能需要换个角度思考", "建议换一种方式或角度来看待问题，可能会有新的发现或解决方案。"}, {"Consider a different perspective", "It is suggested to view the issue from a different way or perspective, which may lead to new findings or solutions."}},
    {{"行动起来！", "鼓励立即采取行动或实施计划，不要犹豫。"}, {"Take action!", "Encourages immediate action or implementation of plans without hesitation."}},
    {{"保持开放心态", "对新想法和不同的观点保持开放和接受的态度。"}, {"Keep an open mind", "Stay open and receptive to new ideas and different perspectives."}},
    {{"现在就做", "鼓励立刻行动，不要拖延。"}, {"Do it now", "Encourages immediate action without delay."}},
    {{"保持冷静", "在面对挑战或困难时，保持冷静和理智。"}, {"Stay calm", "Stay calm and rational when facing challenges or difficulties."}},
    {{"小心行事", "在做出任何行动或决定之前，谨慎考虑和评估。"}, {"Be cautious", "Consider and evaluate carefully before taking any action or decision."}},
    {{"聆听内心的声音", "倾听自己内心的声音和直觉，它们会指引你正确的方向。"}, {"Listen to your inner voice", "Listen to your inner voice and intuition; they will guide you in the right direction."}},
    {{"勇敢面对挑战", "勇敢地面对困难和挑战，它们会让你更强大。"}, {"Face challenges bravely", "Face difficulties and challenges bravely; they will make you stronger."}},
    {{"寻找平衡", "在生活和工作之间寻找平衡，保持身心健康。"}, {"Find balance", "Find balance between life and work, and maintain physical and mental health."}},
    {{"懂得放手", "学会放下过去的事情和不必要的负担，让自己更轻松。"}, {"Learn to let go", "Learn to let go of the past and unnecessary burdens, and make yourself lighter."}},
    {{"抓住机会", "抓住每一个机会，它可能改变你的生活。"}, {"Seize the opportunity", "Seize every opportunity; it may change your life."}},
    {{"专注于当前", "集中精力和注意力在当前的事情上，不要过于纠结过去或未来。"}, {"Focus on the present", "Focus your energy and attention on the present; don't dwell too much on the past or future."}},
    {{"保持积极乐观", "保持积极乐观的心态，即使面临困难也要坚持向前。"}, {"Stay positive and optimistic", "Stay positive and optimistic; persevere even in the face of difficulties."}},
    {{"学习和成长", "不断学习和成长，这是不断进步的关键。"}, {"Learn and grow", "Keep learning and growing; it's the key to continuous improvement."}},
    {{"感恩身边的人", "感恩身边的亲人和朋友，他们是你生活中的支柱和动力。"}, {"Be grateful for those around you", "Be grateful for your loved ones and friends; they are the pillars and motivation in your life."}},
    {{"找到生活的意义", "寻找生活的意义和目标，这会给你力量和动力。"}, {"Find meaning in life", "Find meaning and purpose in life; it will give you strength and motivation."}},
    {{"寻求支持和帮助", "当需要时，寻求他人的支持和帮助，不要孤军奋战。"}, {"Seek support and help", "Seek support and help from others when needed; don't fight alone."}},
    {{"展现真正的自己", "勇敢展现真实的自我，不要害怕被别人认识。"}, {"Show your true self", "Bravely show your true self; don't be afraid of being known by others."}},
    {{"发挥潜力", "发挥你的潜力和才能，做自己想做的事情。"}, {"Unleash your potential", "Unleash your potential and talent; do what you want to do."}},
    {{"坚持到底", "坚持不懈，直到达到目标或完成任务。"}, {"Persist until the end", "Persist relentlessly until you reach your goal or complete the task."}},
    {{"克服恐惧", "勇敢面对恐惧和挑战，它们是成长的机会。"}, {"Overcome fear", "Face fear and challenges bravely; they are opportunities for growth."}},
    {{"寻找平静", "在忙碌的生活中寻找内心的平静和宁静。"}, {"Seek peace", "Find inner peace and tranquility amidst busy life."}},
    {{"相信自己", "相信自己的能力和价值，你可以做到。"}, {"Believe in yourself", "Believe in your abilities and worth; you can do it."}},
    {{"保持热情", "保持对生活和工作的热情，它会驱使你前进。"}, {"Keep your passion alive", "Keep your passion for life and work alive; it will drive you forward."}},
    {{"欣赏美好的事物", "欣赏周围美好的事物和人，让生活更加丰富。"}, {"Appreciate the beauty", "Appreciate the beauty and goodness around you; it enriches life."}},
    {{"练习宽容和理解", "学会宽容和理解，尊重他人的观点和选择。"}, {"Practice tolerance and understanding", "Learn to be tolerant and understanding; respect others' views and choices."}},
    {{"适应变化", "适应生活和工作中的变化，灵活应对。"}, {"Adapt to change", "Adapt to changes in life and work; be flexible."}},
    {{"珍惜每一刻", "珍惜当下的每一刻，它们都是独一无二的。"}, {"Treasure every moment", "Treasure every moment; they are all unique."}},
    {{"感受快乐", "尽情感受快乐和喜悦，它是生活的美好之一。"}, {"Experience happiness", "Experience joy and happiness to the fullest; it's one of life's beauties."}},
    {{"坚持希望", "保持对未来的希望和信心，它会指引你前进。"}, {"Hold on to hope", "Hold on to hope and confidence in the future; it will guide you forward."}},
    {{"学会感恩", "学会感恩和珍惜，这会带来更多的幸福感。"}, {"Learn gratitude", "Learn to be grateful and appreciative; it brings more happiness."}},
    {{"寻找解决方案", "寻找解决问题的方案和方法，不要被困扰所困住。"}, {"Find solutions", "Seek solutions and methods to solve problems; don't be trapped by troubles."}},
    {{"放下过去", "放下过去的情感和怨恨，让自己解脱。"}, {"Let go of the past", "Let go of past emotions and resentments; free yourself."}},
    {{"追求卓越", "追求卓越和优秀，不断提高自己的水平。"}, {"Strive for excellence", "Strive for excellence and greatness; continuously improve yourself."}},
    {{"专注于解决问题", "集中精力和注意力在解决问题上，而不是抱怨困难。"}, {"Focus on solutions", "Focus your energy and attention on solving problems instead of complaining about difficulties."}},
    {{"保持真诚", "保持真诚和坦率，不要伪装自己。"}, {"Stay true", "Stay true and honest; don't pretend to be someone you're not."}},
    {{"探索未知", "勇敢探索未知领域和可能性，它们充满惊喜。"}, {"Explore the unknown", "Bravely explore the unknown and possibilities; they are full of surprises."}},
    {{"培养耐心", "培养耐心和毅力，面对困难时保持冷静。"}, {"Develop patience", "Develop patience and perseverance; stay calm in the face of difficulties."}},
    {{"接受挑战", "勇敢接受挑战和机遇，它们可以带来成长和进步。"}, {"Accept the challenge", "Bravely accept challenges and opportunities; they can bring growth and progress."}},
    {{"感受爱的力量", "感受爱的力量和温暖，它能够带来幸福和满足感。"}, {"Feel the power of love", "Feel the power and warmth of love; it brings happiness and fulfillment."}},
    {{"坚持自我", "坚持做真实的自己，不要被外界影响。"}, {"Stay true to yourself", "Stay true to who you are; don't be influenced by others."}},
    {{"展现勇气", "展现勇气和坚强，面对困难和挑战。"}, {"Show courage", "Show courage and strength in facing difficulties and challenges."}},
    {{"追求梦想", "追求自己的梦想和目标，不要放弃。"}, {"Chase your dreams", "Pursue your dreams and goals; don't give up."}},
    {{"享受当下", "享受当下的美好和快乐，不要过于担忧未来。"}, {"Enjoy the moment", "Enjoy the beauty and joy of the moment; don't worry too much about the future."}},
    {{"寻找灵感", "寻找灵感和创意，它们会激发你的想象力。"}, {"Find inspiration", "Find inspiration and creativity; they will ignite your imagination."}},
    {{"拥抱改变", "积极面对和接受变化，它们是成长的机会。"}, {"Embrace change", "Embrace and accept change positively; they are opportunities for growth."}},
    {{"学习弹性", "学会适应和恢复力，从失败中学习并前进。"}, {"Learn resilience", "Learn to adapt and bounce back; learn from failures and move forward."}},
    {{"寻找美好", "在生活中寻找美好和愉悦，让心灵充满喜悦。"}, {"Seek beauty", "Seek beauty and joy in life; let your soul be filled with delight."}},
    {{"掌握机会", "抓住每一个机会和可能性，它们可能改变你的生活。"}, {"Seize the opportunity", "Seize every opportunity and possibility; they may change your life."}},
    {{"尊重他人", "尊重他人的观点和选择，建立良好的人际关系。"}, {"Respect others", "Respect others' views and choices; build good interpersonal relationships."}},
    {{"发挥创意", "释放自己的创意和想象力，创造独特的价值。"}, {"Unleash creativity", "Unleash your creativity and imagination; create unique value."}},
    {{"心怀希望", "无论面对多大的挑战，保持对未来的希望和信心。"}, {"Hold hope in your heart", "No matter how big the challenge, hold hope and confidence in the future."}},
    {{"乐观面对困难", "乐观地面对困难和挑战，相信自己能够克服一切。"}, {"Face difficulties with optimism", "Face difficulties and challenges with optimism, believing you can overcome anything."}},
    {{"珍惜友谊", "珍惜和维护友谊，它们是生活中的宝贵财富。"}, {"Treasure friendships", "Treasure and nurture friendships; they are precious treasures in life."}},
    {{"追求平等", "倡导和追求平等和公正，尊重每个人的权利。"}, {"Strive for equality", "Advocate and strive for equality and justice, respecting everyone's rights."}},
    {{"鼓励他人", "鼓励和支持他人，共同成长和进步。"}, {"Encourage others", "Encourage and support others; grow and progress together."}},
    {{"持之以恒", "坚持不懈，追求目标的过程中不断努力。"}, {"Persevere", "Persevere and continuously strive for goals."}},
    {{"感恩每一天", "感恩每一天的美好和机会，珍惜生命。"}, {"Be grateful every day", "Be grateful for the beauty and opportunities of each day; cherish life."}},
    {{"追求和平", "积极倡导和追求和平，促进社会稳定与进步。"}, {"Pursue peace", "Actively advocate and pursue peace, promoting social stability and progress."}},
    {{"拥抱自由", "珍视和捍卫个人自由和权利，不受束缚。"}, {"Embrace freedom", "Value and defend personal freedom and rights; don't be constrained."}},
    {{"寻找乐趣", "在生活中寻找快乐和乐趣，让心灵愉悦。"}, {"Find joy", "Find happiness and joy in life; let your soul be delighted."}},
    {{"培养同理心", "培养同情心和理解力，关心他人的感受。"}, {"Cultivate empathy", "Cultivate sympathy and understanding; care about others' feelings."}},
    {{"展现善良", "展现善良和同情心，为他人带来温暖与希望。"}, {"Show kindness", "Show kindness and compassion, bringing warmth and hope to others."}},
    {{"享受孤独", "学会享受独处的时光，思考和反思。"}, {"Enjoy solitude", "Learn to enjoy solitude; use it for reflection and introspection."}},
    {{"探索自我", "探索自己的内心和潜力，发现更多可能性。"}, {"Explore yourself", "Explore your inner self and potential; discover more possibilities."}},
    {{"尊重他人意见", "尊重他人的观点和看法，保持开放和包容。"}, {"Respect others' opinions", "Respect others' viewpoints and opinions; maintain openness and inclusivity."}},
    {{"追求知识", "不断学习和探索知识，拓宽视野。"}, {"Pursue knowledge", "Continuously learn and explore knowledge; broaden your horizons."}},
    {{"尊重自然", "尊重和保护自然环境，珍惜地球资源。"}, {"Respect nature", "Respect and protect the natural environment; cherish Earth's resources."}},
    {{"珍惜时光", "珍惜每一刻的时光，不要虚度年华。"}, {"Cherish time", "Cherish every moment of time; don't waste your years."}},
    {{"学会宽容", "学会宽容和理解，尊重多样性。"}, {"Learn tolerance", "Learn tolerance and understanding; respect diversity."}},
    {{"持续成长", "持续学习和成长，不断提升自我。"}, {"Keep growing", "Keep learning and growing; continuously improve yourself."}},
    {{"保持弹性", "保持弹性和适应能力，应对变化。"}, {"Stay resilient", "Stay resilient and adaptable; cope with changes."}},
    {{"保持平衡", "保持生活和工作的平衡，注重身心健康。"}, {"Maintain balance", "Maintain balance between life and work; prioritize physical and mental health."}},
    {{"感受自然", "感受大自然的美妙和神奇，与自然和谐共处。"}, {"Feel nature", "Experience the beauty and wonder of nature; live in harmony with it."}},
    {{"寻找希望", "在困难和挑战中寻找希望和光明。"}, {"Find hope", "Find hope and light in difficulties and challenges."}},
    {{"培养梦想", "培养和实现自己的梦想和愿望。"}, {"Nurture dreams", "Nurture and fulfill your dreams and aspirations."}},
    {{"学会包容", "学会包容和接纳不同的观点和人群。"}, {"Learn inclusivity", "Learn to be inclusive and embrace different viewpoints and people."}},
    {{"享受创造", "享受创造和创新的乐趣，发挥想象力。"}, {"Enjoy creation", "Enjoy the joy of creation and innovation; unleash your imagination."}},
    {{"寻找平静", "寻找内心的平静和宁静，远离喧嚣。"}, {"Seek tranquility", "Seek inner peace and tranquility; stay away from the noise."}},
    {{"培养爱心", "培养善良和同情心，帮助他人。"}, {"Cultivate kindness", "Cultivate kindness and compassion; help others."}},
    {{"寻找快乐", "寻找真正的快乐和幸福，源于内心。"}, {"Find happiness", "Find true happiness and joy; it comes from within."}},
    {{"拥抱挑战", "勇敢面对挑战和困难，不断成长。"}, {"Embrace challenges", "Bravely face challenges and difficulties; continuously grow."}},
    {{"感受孩子的纯真", "感受孩子们的纯真和活力，保持童心。"}, {"Feel the innocence of children", "Feel the innocence and vitality of children; keep the childlike heart."}},
    {{"展示勇气", "展示勇气和坚定，不畏困难和挑战。"}, {"Demonstrate courage", "Demonstrate courage and determination; fear no difficulties or challenges."}},
    {{"保持独立", "保持独立和自主，做出自己的选择。"}, {"Maintain independence", "Maintain independence and autonomy; make your own choices."}},
    {{"寻找爱的力量", "感受爱的力量和温暖，化解矛盾。"}, {"Find the power of love", "Feel the power and warmth of love; resolve conflicts."}},
    {{"鼓励创新", "鼓励创新和创造，推动社会进步。"}, {"Encourage innovation", "Encourage innovation and creation; promote social progress."}},
    {{"保持专注", "保持专注和目标，追求卓越。"}, {"Stay focused", "Stay focused and goal-oriented; strive for excellence."}},
    {{"欢迎变化", "欢迎变化和挑战，不断适应。"}, {"Embrace change", "Embrace change and challenges; continuously adapt."}},
    {{"寻找正念", "培养正念和平静心态，提升生活质量。"}, {"Find mindfulness", "Cultivate mindfulness and calmness; improve quality of life."}},
    {{"去吧", "勇敢前行，追逐梦想。"}, {"Go ahead", "Bravely move forward and chase your dreams."}},
    {{"坚定不移", "坚定不移，战胜一切困难。"}, {"Stay strong", "Stay strong and overcome all obstacles."}},
    {{"不推荐", "不建议继续这个方向，需要重新评估。"}, {"Not recommended", "Not recommended to proceed in this direction; reevaluation is needed."}},
    {{"暂停", "建议暂停当前行动，等待更好的时机。"}, {"Pause", "It's recommended to pause current actions and wait for a better opportunity."}},
    {{"慎重考虑", "建议仔细考虑再行动，避免潜在风险。"}, {"Consider carefully", "It's recommended to consider carefully before taking action to avoid potential risks."}},
    {{"需重新计划", "建议重新规划和安排，优化行动方案。"}, {"Needs re-planning", "Recommended to re-plan and optimize the action plan."}},
    {{"不适合", "不适合当前情况，需要寻找其他方案。"}, {"Not suitable", "Not suitable for the current situation; need to explore other options."}},
    {{"保持沉默", "建议暂时保持沉默，等待更多信息或进展。"}, {"Keep silent", "It's recommended to keep silent for now and wait for more information or progress."}},
    {{"保持观望", "建议暂时保持中立态度，观察情况变化。"}, {"Stay neutral", "It's recommended to stay neutral for now and observe changes in the situation."}}
};

#define ANSWER_COUNT (sizeof(answer_list)/sizeof(answer_list[0]))

// 使用示例
// int idx = rand() % ANSWER_COUNT;
// const char* zh_title = answer_list[idx][0][0];
// const char* zh_desc  = answer_list[idx][0][1];
// const char* en_title = answer_list[idx][1][0];
// const char* en_desc  = answer_list[idx][1][1];
